# SonarCloud — StockPro
sonar.organization=wassimhaoues
sonar.projectKey=wassimhaoues_stock_app
sonar.projectName=stock_app

# Sources: Java backend + Angular frontend
sonar.sources=backend/src/main/java,frontend/src/app
sonar.tests=backend/src/test/java,frontend/src/app
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/app/**/*.spec.ts

# Java
sonar.java.binaries=backend/target/classes
sonar.java.libraries=backend/target/dependency
sonar.java.source=17
sonar.java.target=17
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/stockpro-frontend/lcov.info

# Exclusions (analysis)
sonar.exclusions=\
  frontend/node_modules/**,\
  frontend/dist/**,\
  frontend/coverage/**,\
  **/*.spec.ts,\
  **/test/**

# Exclusions (coverage) — boilerplate with no business logic
sonar.coverage.exclusions=\
  backend/src/main/java/com/wassim/stock/dto/**,\
  backend/src/main/java/com/wassim/stock/entity/**,\
  backend/src/main/java/com/wassim/stock/repository/**,\
  backend/src/main/java/com/wassim/stock/config/**,\
  backend/src/main/java/com/wassim/stock/exception/**,\
  backend/src/main/java/com/wassim/stock/StockBackendApplication.java,\
  frontend/src/app/core/models/**,\
  frontend/src/app/main.ts

# Block the pipeline until the Quality Gate result is available
sonar.qualitygate.wait=true
