# SonarCloud — StockPro
sonar.organization=wassimhaoues
sonar.projectKey=wassimhaoues_stock_app
sonar.projectName=stock_app

# Sources: Java backend + Angular frontend
sonar.sources=backend/src/main/java,frontend/src/app
sonar.tests=backend/src/test/java

# Java
sonar.java.binaries=backend/target/classes
sonar.java.source=17
sonar.java.target=17
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=\
  frontend/node_modules/**,\
  frontend/dist/**,\
  frontend/coverage/**,\
  **/*.spec.ts,\
  **/test/**

# Block the pipeline until the Quality Gate result is available
sonar.qualitygate.wait=true
