services:
  stock-phpmyadmin:
    image: phpmyadmin:latest
    container_name: stock-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3307
      UPLOAD_LIMIT: 512M
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:8084:80"
