apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: stockpro
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: stockpro-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
