spring.datasource.url=jdbc:mysql://${DB_HOST:stock-db}:${DB_PORT:3306}/${DB_NAME:stock_app_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:Wassimhws}
spring.datasource.password=${DB_PASSWORD:WassimStudy+2025}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
